version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - sqlite_data:/app/db_data
    environment:
      - DEBUG=False
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    restart: always

volumes:
  sqlite_data: