version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./db.sqlite3:/app/db.sqlite3
    environment:
      - DEBUG=False
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    restart: always

volumes:
  sqlite_data: