# Generated by Django 5.1.6 on 2026-03-09 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_drug_manufacturer_drug_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demands', to='core.institution')),
            ],
            options={
                'ordering': ['-year', '-month', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DemandItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.demand')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demand_items', to='core.drug')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='demand',
            constraint=models.UniqueConstraint(fields=('institution', 'year', 'month'), name='uniq_demand_institution_year_month'),
        ),
        migrations.AddConstraint(
            model_name='demanditem',
            constraint=models.UniqueConstraint(fields=('demand', 'drug'), name='uniq_demanditem_demand_drug'),
        ),
    ]
