# Generated by Django 5.1.6 on 2026-03-09 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_demand_demanditem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('limit_qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_limits', to='core.drug')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_limits', to='core.institution')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('issued_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_issues', to='core.drug')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_issues', to='core.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='core.drug')),
            ],
        ),
    ]
