# Generated by Django 6.0.2 on 2026-03-15 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_annuallimit_monthlyissue_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeedRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('yearly_need', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('quarterly_need', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('dpm_need', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('amb_rec_need', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('given_dpm', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('remaining', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='need_rows', to='core.drug')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='need_rows', to='core.institution')),
            ],
            options={
                'unique_together': {('institution', 'drug', 'year')},
            },
        ),
    ]
