# Generated by Django 6.0.2 on 2026-03-17 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_price_base_price_price_referent_price_15_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='end_date',
        ),
    ]
