# Generated by Django 6.0.2 on 2026-03-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_price_end_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annuallimit',
            options={'ordering': ['-year', 'institution__name', 'drug__name']},
        ),
        migrations.AlterModelOptions(
            name='drug',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='monthlyissue',
            options={'ordering': ['-year', 'institution__name', 'drug__name']},
        ),
        migrations.AlterModelOptions(
            name='needrow',
            options={'ordering': ['-year', 'institution__name', 'drug__name']},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['-start_date', '-id']},
        ),
        migrations.AlterUniqueTogether(
            name='needrow',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='monthlyissue',
            name='month',
        ),
        migrations.RemoveField(
            model_name='price',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='price',
            name='referent_price_15',
        ),
        migrations.RemoveField(
            model_name='price',
            name='sale_price_15',
        ),
        migrations.AlterField(
            model_name='monthlyissue',
            name='issued_qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='monthlyissue',
            name='year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='monthlyissue',
            constraint=models.UniqueConstraint(fields=('institution', 'drug', 'year'), name='uniq_monthlyissue_institution_drug_year'),
        ),
        migrations.AddConstraint(
            model_name='needrow',
            constraint=models.UniqueConstraint(fields=('institution', 'drug', 'year'), name='uniq_needrow_institution_drug_year'),
        ),
        migrations.RemoveField(
            model_name='needrow',
            name='given_dpm',
        ),
        migrations.RemoveField(
            model_name='needrow',
            name='remaining',
        ),
        migrations.RemoveField(
            model_name='needrow',
            name='remaining_percent',
        ),
    ]
