# Generated by Django 6.0.2 on 2026-03-28 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_annuallimit_options_alter_drug_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='price',
        ),
    ]
