# Generated by Django 6.0.2 on 2026-03-28 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_drug_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annuallimit',
            name='drug',
        ),
        migrations.RemoveField(
            model_name='annuallimit',
            name='institution',
        ),
        migrations.RemoveConstraint(
            model_name='demand',
            name='uniq_demand_institution_year_month',
        ),
        migrations.RemoveConstraint(
            model_name='demanditem',
            name='uniq_demanditem_demand_drug',
        ),
        migrations.DeleteModel(
            name='AnnualLimit',
        ),
        migrations.RemoveField(
            model_name='demanditem',
            name='demand',
        ),
        migrations.RemoveField(
            model_name='demanditem',
            name='drug',
        ),
        migrations.DeleteModel(
            name='Demand',
        ),
        migrations.DeleteModel(
            name='DemandItem',
        ),
    ]
