# Generated by Django 5.1.6 on 2026-04-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auditlog'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='price',
            constraint=models.UniqueConstraint(fields=('drug', 'start_date'), name='unique_price_drug_start_date'),
        ),
    ]
