# Generated by Django 5.1.6 on 2026-04-21 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_price_unique_price_drug_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyissue',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_issues', to='core.drug'),
        ),
        migrations.AlterField(
            model_name='monthlyissue',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_issues', to='core.institution'),
        ),
        migrations.AlterField(
            model_name='needrow',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='need_rows', to='core.institution'),
        ),
        migrations.AlterField(
            model_name='price',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='core.drug'),
        ),
    ]
