# Generated by Django 6.0.2 on 2026-04-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_monthlyissue_drug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password_policy',
            field=models.CharField(choices=[('simple', 'Simple'), ('medium', 'Medium'), ('strong', 'Strong')], default='medium', max_length=20),
        ),
    ]
