# Generated by Django 6.0.2 on 2026-04-27 06:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_monthlyissue_drug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='inn',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.MinLengthValidator(9)], verbose_name='STIR(INN)'),
        ),
    ]
