# Generated by Django 6.0.2 on 2026-04-24 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_userprofile_must_change_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needrow',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='need_rows', to='core.drug'),
        ),
    ]
