# Generated by Django 5.1.6 on 2026-05-06 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_needrow_drug'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='inn',
            field=models.CharField(blank=True, db_index=True, default='', max_length=9, validators=[django.core.validators.RegexValidator(message='ИНН 9 та рақамдан иборат бўлиши керак.', regex='^\\d{9}$')]),
        ),
        migrations.AddConstraint(
            model_name='institution',
            constraint=models.UniqueConstraint(condition=models.Q(('inn', ''), _negated=True), fields=('inn',), name='unique_institution_inn_when_filled'),
        ),
    ]
