# Generated by Django 5.1.6 on 2026-05-09 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_institution_inn_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NeedAddition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('added_qty', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('addition_date', models.DateField()),
                ('reason', models.TextField(blank=True, default='')),
                ('doc_number', models.CharField(blank=True, default='', max_length=120)),
                ('doc_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_need_additions', to=settings.AUTH_USER_MODEL)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='need_additions', to='core.drug')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='need_additions', to='core.institution')),
            ],
            options={
                'ordering': ['-year', 'institution__name', 'drug__name', '-addition_date', '-id'],
                'indexes': [models.Index(fields=['institution', 'drug', 'year'], name='idx_needaddition_main_key'), models.Index(fields=['year', 'addition_date'], name='idx_needaddition_year_date')],
                'constraints': [models.CheckConstraint(condition=models.Q(('added_qty__gt', 0)), name='needaddition_added_qty_gt_zero')],
            },
        ),
    ]
