# Generated by Django 5.1.6 on 2026-05-10 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_needaddition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='needaddition',
            name='needaddition_added_qty_gt_zero',
        ),
        migrations.AddField(
            model_name='needaddition',
            name='amb_rec_need_add',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='needaddition',
            name='cancel_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='needaddition',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='needaddition',
            name='dpm_need_add',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='needaddition',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='needaddition',
            name='need_row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='additions', to='core.needrow'),
        ),
        migrations.AddField(
            model_name='needaddition',
            name='total_additional_need',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='needaddition',
            name='reason',
            field=models.CharField(choices=[('base_underestimated', 'Йил бошида кам ҳисобланган'), ('new_department', 'Янги бўлим очилди'), ('patient_increase', 'Беморлар сони ошди'), ('new_clinic', 'Янги клиника иш бошлади'), ('ssv_order', 'ССВ топшириғи / қайта тақсимот'), ('correction', 'Ҳисоб-китобни тузатиш'), ('other', 'Бошқа')], default='other', max_length=64),
        ),
        migrations.AddIndex(
            model_name='needaddition',
            index=models.Index(fields=['need_row', 'is_active'], name='idx_needaddition_row_active'),
        ),
        migrations.AddConstraint(
            model_name='needaddition',
            constraint=models.CheckConstraint(condition=models.Q(('dpm_need_add__gte', 0), ('amb_rec_need_add__gte', 0)), name='needaddition_parts_non_negative'),
        ),
    ]
