# Generated by Django 5.1.6 on 2026-05-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_needaddition_needaddition_added_qty_gt_zero_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drug',
            options={'ordering': ['name', 'dosage_value', 'dosage_unit', 'package_quantity', 'dosage_form']},
        ),
        migrations.AddField(
            model_name='drug',
            name='dosage_form',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='drug',
            name='dosage_unit',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='drug',
            name='dosage_value',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='drug',
            name='full_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='drug',
            name='mnn_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='drug',
            name='package_quantity',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='drug',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
