# Generated by Django 5.1.6 on 2026-05-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_drug_options_drug_dosage_form_drug_dosage_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('dosage_unit', 'Доза бирлиги'), ('dosage_form', 'Дори тури'), ('measure_unit', 'Ўлчов бирлиги')], db_index=True, max_length=30)),
                ('name', models.CharField(max_length=80)),
                ('aliases', models.TextField(blank=True, default='', help_text='Алиаслар: масалан гель, гел; таблетка, табл; упаковка, уп.')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['kind', 'sort_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'name'), name='uniq_drug_option_kind_name')],
            },
        ),
    ]
