# Generated by Django 5.1.6 on 2026-05-17 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_drugoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='control_group',
            field=models.CharField(choices=[('general', 'Оддий препарат'), ('narcotic', 'Гиёҳвандлик воситалари'), ('psychotropic', 'Психотроп моддалар'), ('strong', 'Кучли таъсир қилувчи препаратлар'), ('precursor', 'Прекурсорлар')], db_index=True, default='general', max_length=30),
        ),
    ]
